### ISSUE TITLE
unattended-upgrades

### ISSUE THREAD

**Issue by meyskens** [scaleway/image-ubuntu#28]
I noticed unattended upgrades is not on the image. I think it should be a good idea to add and enable it by default on the system as it could save a lot of work for sysmins when an important security update comes arround.

**Comment by aimxhaisse** [comment]
I think we could add a guide to explain how to enable unattended upgrades, but considering we have some things that are more likely to break when upgrading, I'd rather let it disabled by default, like in upstream distributions.

Just to illustrate: we had to remove the (x)nbd-client from standard distributions because upon upgrades of this package, it does a `rmmod nbd` and then re-inserts it, which obviously doesn't work on root mounted filesystems via NBD ; we also had a similar issue with systemd.

**Comment by mgedmin** [comment]
I was unable to find any bugs about upgrades breaking when root is mounted on nbd in [Ubuntu's](https://bugs.launchpad.net/ubuntu/+source/nbd) and  [Debian's](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=nbd-client;dist=unstable) bugtrackers.
